name: 'CI/CD Study'
description: 'Say Hello'
author: 'KDH'

runs:
  using: 'node20'
  main: 'dist/index.js'

inputs:
  name:
    description: 'The name of the person to greet'
    required: true
    default: 'KDH'
  GITHUB_TOKEN:
    description: 'The GitHub token for authentication.'
    required: true
  label:
    description: 'The label to be applied to the pull request.'
    required: true

