name: "Thank you"
description: "Replying to participants"
runs:
  using: "node16"
  main: "index.js"
inputs:
  token:
    description: "github token"
    required: true    # Action은 Token이라는 값을 필수로 가져야 한다.
